import Seo from '../../components/Seo';
import * as XLSX from 'xlsx';

export default function Importer(){
  const onFile = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const data = await file.arrayBuffer();
    let rows = [];

    if (file.name.toLowerCase().endsWith('.xlsx')) {
      const wb = XLSX.read(data);
      const ws = wb.Sheets[wb.SheetNames[0]];
      rows = XLSX.utils.sheet_to_json(ws, { defval: '' });
    } else {
      // Naive CSV – XLSX kann auch CSV
      const wb = XLSX.read(data, { type: 'array' });
      const ws = wb.Sheets[wb.SheetNames[0]];
      rows = XLSX.utils.sheet_to_json(ws, { defval: '' });
    }

    // Map in QUESTIONS
    const QUESTIONS = rows.map((r, i) => {
      const answers = [
        { id: 'a', text: String(r.a || '').trim() },
        { id: 'b', text: String(r.b || '').trim() },
        { id: 'c', text: String(r.c || '').trim() },
        { id: 'd', text: String(r.d || '').trim() },
      ].filter(x => x.text);
      const corr = String(r.correct || '').split('|').map(s => s.trim()).filter(Boolean);
      const countries = String(r.countries || 'DE').split('|').map(s => s.trim().toUpperCase());
      return {
        id: String(r.id || `q_${i+1}`),
        countries,
        topic: String(r.topic || 'Wildkunde'),
        q: String(r.q || '').trim(),
        answers,
        correct: corr.length ? corr : ['a'],
        explain: String(r.explain || '').trim()
      };
    });

    const header = `// Generated by admin/import. Edit with care.\n`;
    const code = `${header}export const QUESTIONS = ${JSON.stringify(QUESTIONS, null, 2)};\n\nexport function filterQuestions({ country = 'DE', topic = 'Alle', count = 10 }) {
  const pool = QUESTIONS.filter(q => (q.countries.includes(country)) && (topic === 'Alle' || q.topic === topic));
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}\n`;

    const blob = new Blob([code], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'questions.js'; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <Seo title="Admin – Fragen Import (Excel/CSV)" />
      <section className="section">
        <div className="container" style={{maxWidth:760}}>
          <h1>Fragen Import</h1>
          <div className="card">
            <p>Upload einer <b>.xlsx</b> oder <b>.csv</b> mit Spalten:</p>
            <pre style={{whiteSpace:'pre-wrap', background:'rgba(0,0,0,.04)', padding:10, borderRadius:10}}>
id | countries | topic | q | a | b | c | d | correct | explain
z.B. countries: DE|AT|CH · correct: a|c
            </pre>
            <input type="file" accept=".xlsx,.csv" onChange={onFile} />
            <p className="small" style={{marginTop:8}}>Nach dem Import erhältst du eine <code>questions.js</code> zum Download – diese Datei einfach nach <code>/data/questions.js</code> ins Repo legen & committen.</p>
          </div>
        </div>
      </section>
    </>
  );
}
