// Lizenzierte Originalaufnahmen. Quellen- und Lizenznachweise auch in public/lernen/{pflanzen,spuren}/bildnachweise.json.
export const plantPhotos = {
  "rotbuche": {
    "id": "rotbuche",
    "src": "/lernen/pflanzen/rotbuche.jpg",
    "author": "Dominicus Johannes Bergsma",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blad_van_beuk_(Fagus_sylvatica)_02.JPG",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Blad_van_beuk_%28Fagus_sylvatica%29_02.JPG/1280px-Blad_van_beuk_%28Fagus_sylvatica%29_02.JPG",
    "caption": "Beech leaf (Fagus sylvatica).",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Echte Aufnahme eines Rotbuchenblatts."
  },
  "stieleiche": {
    "id": "stieleiche",
    "src": "/lernen/pflanzen/stieleiche.jpg",
    "author": "AnRo0002",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:20180703Quercus_robur2.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/20180703Quercus_robur2.jpg/1280px-20180703Quercus_robur2.jpg",
    "caption": "Stieleiche (Quercus robur) im Landschaftsschutzgebiet „Hockenheimer Rheinbogen“",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Echte Aufnahme von Stieleichenblättern mit rundlichen Blattgallen, keine Eicheln.",
    "displayCaption": "Die runden Gebilde im Stieleichenfoto sind Blattgallen, keine Eicheln. Zur Fruchtbestimmung brauchst du zusätzlich echte Eichelstände."
  },
  "haengebirke": {
    "id": "haengebirke",
    "src": "/lernen/pflanzen/haengebirke.jpg",
    "author": "Nefronus",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Betula_pendula_leaves.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/Betula_pendula_leaves.jpg/1280px-Betula_pendula_leaves.jpg",
    "caption": "leaves of Betula pendula in May",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 750,
    "height": 1000,
    "alt": "Echte Aufnahme von Hängebirkenblättern."
  },
  "bergahorn": {
    "id": "bergahorn",
    "src": "/lernen/pflanzen/bergahorn.jpg",
    "author": "Willow",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acer_pseudoplatanus_002.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Acer_pseudoplatanus_002.jpg/1280px-Acer_pseudoplatanus_002.jpg",
    "caption": "Sycamore Maple (Acer pseudoplatanus), Inflorescence, Location: Cappel, Hesse, Germany",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Echte Aufnahme des Bergahorns mit hängendem Blütenstand und Blättern."
  },
  "hasel": {
    "id": "hasel",
    "src": "/lernen/pflanzen/hasel.jpg",
    "author": "AnRo0002",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:20130628Corylus_avellana2.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/20130628Corylus_avellana2.jpg/1280px-20130628Corylus_avellana2.jpg",
    "caption": "Haselnuss (Corylus avellana) am Staden in Saarbrücken",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Echte Aufnahme von Haselblättern."
  },
  "eberesche": {
    "id": "eberesche",
    "src": "/lernen/pflanzen/eberesche.jpg",
    "author": "Valju Aloel",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sorbus_aucuparia_fruits.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Sorbus_aucuparia_fruits.jpg",
    "caption": "European Rowan",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 400,
    "height": 400,
    "alt": "Echte Aufnahme von Ebereschenfrüchten und gefiederten Blättern."
  },
  "schlehe": {
    "id": "schlehe",
    "src": "/lernen/pflanzen/schlehe.jpg",
    "author": "Fabrizio Tampieri",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Prunus_spinosa_006.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Prunus_spinosa_006.jpg/1280px-Prunus_spinosa_006.jpg",
    "caption": "Foto di",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Echte Aufnahme blühender Schlehe."
  },
  "weissdorn": {
    "id": "weissdorn",
    "src": "/lernen/pflanzen/weissdorn.jpg",
    "author": "Sdicke",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blatt_des_Eingriffeliger_Wei%C3%9Fdorns_in_Hattingen.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Blatt_des_Eingriffeliger_Wei%C3%9Fdorns_in_Hattingen.jpg/1280px-Blatt_des_Eingriffeliger_Wei%C3%9Fdorns_in_Hattingen.jpg",
    "caption": "Blatt des Eingriffeliger Weißdorns in Hattingen",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Echte Aufnahme eines Blatts des Eingriffeligen Weißdorns."
  },
  "schwarzerle": {
    "id": "schwarzerle",
    "src": "/lernen/pflanzen/schwarzerle.jpg",
    "author": "kallerna",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Public_domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alnus_glutinosa_leaves.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/Alnus_glutinosa_leaves.jpg/1280px-Alnus_glutinosa_leaves.jpg",
    "caption": "Young leaves of Black Alder (Alnus glutinosa).",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1194,
    "height": 1000,
    "alt": "Echte Aufnahme junger Schwarzerlenblätter."
  },
  "fichte": {
    "id": "fichte",
    "src": "/lernen/pflanzen/fichte.jpg",
    "author": "Syrio",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Picea_abies_branch.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Picea_abies_branch.jpg/1280px-Picea_abies_branch.jpg",
    "caption": "Branch of Picea abies, Paludi (Segonzano, Trentino, Italy)",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Echte Aufnahme eines Fichtenzweigs."
  },
  "weisstanne": {
    "id": "weisstanne",
    "src": "/lernen/pflanzen/weisstanne.jpg",
    "author": "Meneerke bloem",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Abies_alba.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Abies_alba.jpg/1280px-Abies_alba.jpg",
    "caption": "Abies alba",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 750,
    "height": 1000,
    "alt": "Echte Aufnahme einer Weißtanne."
  },
  "waldkiefer": {
    "id": "waldkiefer",
    "src": "/lernen/pflanzen/waldkiefer.jpg",
    "author": "USDA-NRCS PLANTS Database / Herman, D.E. et al. 1996. North Dakota tree handbook. USDA NRCS ND State Soil Conservation Committee; NDSU Extension and Western Area Power Admin., Bismarck, ND.",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Public_domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinus_sylvestris_branch.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Pinus_sylvestris_branch.jpg/1280px-Pinus_sylvestris_branch.jpg",
    "caption": "Scots Pine. Branch with pine cones.",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 810,
    "alt": "Echte Aufnahme eines Waldkiefernzweigs mit Zapfen."
  }
};
export const tracksPhotos = {
  "reh-schnee": {
    "id": "reh-schnee",
    "src": "/lernen/spuren/reh-schnee.jpg",
    "author": "W.carter",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Roe_deer_tracks_in_snow_in_Tuntorp.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Roe_deer_tracks_in_snow_in_Tuntorp.jpg/1280px-Roe_deer_tracks_in_snow_in_Tuntorp.jpg",
    "caption": "Roe deer tracks in snow in Tuntorp, Lysekil Municipality, Sweden.",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 667,
    "height": 1000,
    "alt": "Dokumentierte Rehfährte im Schnee.",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "reh-matsch": {
    "id": "reh-matsch",
    "src": "/lernen/spuren/reh-matsch.jpg",
    "author": "W.carter",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Roe_deer_tracks_on_a_muddy_path_in_Tuntorp.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Roe_deer_tracks_on_a_muddy_path_in_Tuntorp.jpg/1280px-Roe_deer_tracks_on_a_muddy_path_in_Tuntorp.jpg",
    "caption": "Roe deer tracks on a muddy path in Tuntorp, Brastad, Lysekil Municipality, Sweden.",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Dokumentierte Rehfährte auf schlammigem Boden.",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "fuchs-schnee": {
    "id": "fuchs-schnee",
    "src": "/lernen/spuren/fuchs-schnee.jpg",
    "author": "Alan Hughes",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fox_tracks_-_geograph.org.uk_-_6739732.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Fox_tracks_-_geograph.org.uk_-_6739732.jpg/1280px-Fox_tracks_-_geograph.org.uk_-_6739732.jpg",
    "caption": "Fox tracks ",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 750,
    "height": 1000,
    "alt": "Als Fuchsspur dokumentierte Abdrücke im Schnee.",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/"
  },
  "hase-schnee": {
    "id": "hase-schnee",
    "src": "/lernen/spuren/hase-schnee.jpg",
    "author": "Pöllö",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hare_tracks_on_snow_in_forest_Laajasalo_Helsinki.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Hare_tracks_on_snow_in_forest_Laajasalo_Helsinki.jpg/1280px-Hare_tracks_on_snow_in_forest_Laajasalo_Helsinki.jpg",
    "caption": "Hare tracks on snow in forest. Picture taken in Laajasalo, Helsinki, Finland.",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 900,
    "alt": "Dokumentierte Hasenspur im verschneiten Wald.",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/"
  },
  "otter-sand": {
    "id": "otter-sand",
    "src": "/lernen/spuren/otter-sand.jpg",
    "author": "Mike Pennington",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Otter_tracks_on_Skaw_beach_-_geograph.org.uk_-_4723836.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Otter_tracks_on_Skaw_beach_-_geograph.org.uk_-_4723836.jpg",
    "caption": "Otter tracks on Skaw beach ",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1024,
    "height": 576,
    "alt": "Als Fischotterspur dokumentierte Abdrücke am Strand von Skaw.",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/"
  },
  "biber-nagespur": {
    "id": "biber-nagespur",
    "src": "/lernen/spuren/biber-nagespur.jpg",
    "author": "Gzzz",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tree_gnawed_at_by_european_beaver_01.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Tree_gnawed_at_by_european_beaver_01.jpg/1280px-Tree_gnawed_at_by_european_beaver_01.jpg",
    "caption": "Tree gnawed at by european beavers, at the mouth of the Chamberonne (Lausanne, Switzerland).",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 800,
    "alt": "Dokumentierte Bibernagespuren an einem Baum am Gewässer bei Lausanne.",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "wildschwein-wuehlspur": {
    "id": "wildschwein-wuehlspur",
    "src": "/lernen/spuren/wildschwein-wuehlspur.jpg",
    "author": "Formedivita.it",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tracks-of-wild-boar.jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Tracks-of-wild-boar.jpg",
    "caption": "The boars have dug with their noses in search of roots and insects",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1000,
    "height": 745,
    "alt": "Vom Fotografen dokumentierte Wildschwein-Wühlstelle.",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/"
  },
  "specht-hoehle": {
    "id": "specht-hoehle",
    "src": "/lernen/spuren/specht-hoehle.jpg",
    "author": "TheLivesAroundUs",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Standing_deadwood_with_Woodpecker_holes,_Benhall_Park,_Cheltenham.jpg",
    "originalUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Standing_deadwood_with_Woodpecker_holes%2C_Benhall_Park%2C_Cheltenham.jpg/1280px-Standing_deadwood_with_Woodpecker_holes%2C_Benhall_Park%2C_Cheltenham.jpg",
    "caption": "This image, taken in November 2020, reflects the policy of Cheltenham Borough Council's Tree Department, to leave dead trees standing, where there is no danger to the public, in order to encourage biodiversity. Great spotted Woodpeckers (Dendrocopos major) have been seen in the Park over a number of years. The \"damage\" they do to dead trees benefits many species as it creates nesting holes and creates ways in for fungi and insects. Native trees invariably support many other species, dead or alive. When a tree dies it creates opportunities for different species that might not otherwise thrive in the woodland habitat.",
    "aiGenerated": false,
    "modifications": "Proportional für die Webanzeige verkleinert; JPEG neu komprimiert. Kein generativer Bildinhalt.",
    "width": 1200,
    "height": 800,
    "alt": "Stehendes Totholz mit dokumentierten Spechtlöchern im Benhall Park.",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/"
  }
};
