import { plantPhotos } from "./nature-photos";

// Eigene botanische Kurzfassungen. Artbeschreibungen und Taxonomie:
// InfoFlora / Flora Helvetica, geprüft am 2026-10-04.
const botanicalSource = name => ({ title: "InfoFlora: botanische Artbeschreibung", url: `https://www.infoflora.ch/de/flora/${name.replaceAll(" ", "-")}.html` });
const plant = (id, name, latin, group, features, seasons, confusion, habitat, question, options, answer, explanation) => ({
  id, name, latin, group, features, seasons, confusion, habitat, source: botanicalSource(latin.toLowerCase()), photo: plantPhotos[id],
  quiz: { id: `pflanze-${id}`, title: name, question, options, answer, explanation, source: botanicalSource(latin.toLowerCase()) },
});

export const plantSeasons = [{ id: "fruehling", name: "Frühling" }, { id: "sommer", name: "Sommer" }, { id: "herbst", name: "Herbst" }, { id: "winter", name: "Winter" }];
export const plantGroups = [{ id: "alle", name: "Alle Pflanzen" }, { id: "Laubbaum", name: "Laubbäume" }, { id: "Nadelbaum", name: "Nadelbäume" }, { id: "Strauch", name: "Sträucher" }];

export const plantAtlasEntries = [
  plant("rotbuche", "Rotbuche", "Fagus sylvatica", "Laubbaum", ["Elliptische bis eiförmige Blätter mit fast glattem Rand", "Junge Blattränder tragen feine Wimperhaare", "Meist glatte, graue Rinde"], { fruehling: "Junge Blätter und ihre Wimperhaare ansehen. Blüte meist April bis Mai.", sommer: "Blattform, Rand und Seitennerven gemeinsam vergleichen.", herbst: "Dreikantige Bucheckern in einem weichstacheligen Fruchtbecher ergänzen die Blattmerkmale.", winter: "Die graue, meist glatte Rinde bleibt sichtbar. Zusätzlich Zweige und Knospen mit einem Bestimmungsschlüssel vergleichen." }, "Hainbuche besitzt deutlich gesägte Blätter. Der gemeinsame Name ‚Buche‘ bedeutet keine Zugehörigkeit zur gleichen Gattung.", "Buchenwälder und Mischwälder; Standort und Höhenlage berücksichtigen.", "Welches Merkmal passt zur Rotbuche?", ["Fast glatter Blattrand; junge Blätter am Rand bewimpert", "Fünf tief eingeschnittene Blattlappen", "Immer zwei lange Nadeln in einem Bündel"], 0, "Die Rotbuche besitzt einfache, meist fast ganzrandige Blätter. Blattlappen oder Nadelbündel gehören nicht zu diesem Blattbau."),
  plant("stieleiche", "Stieleiche", "Quercus robur", "Laubbaum", ["Gelappte Blätter mit meist stumpfen Lappen", "Sehr kurzer Blattstiel und kleine Öhrchen am Blattgrund", "Eicheln sitzen an deutlich gestielten Fruchtständen"], { fruehling: "Blüte meist April bis Mai; auf den Blattgrund junger, entfalteter Blätter achten.", sommer: "Blattstiel, Blattgrund und Lappen zusammen prüfen.", herbst: "Der lange Stiel des Eichelstands ist ein wichtiges zusätzliches Merkmal.", winter: "Ein kahler Baum lässt sich nicht nur an einer Eichel im Boden sicher bestimmen. Zweige und weitere Merkmale hinzunehmen." }, "Traubeneiche hat meist längere Blattstiele und weniger deutlich gestielte Eichelstände. Übergänge und Hybriden erschweren die Bestimmung.", "Laubwälder und Waldränder; Eichen können auch angepflanzt sein.", "Worauf bezieht sich ‚Stiel‘ bei der Stieleiche als typisches Unterscheidungsmerkmal?", ["Auf besonders lange Blattstiele", "Auf die gestielten Eichelstände", "Auf einen hohlen Stamm"], 1, "Stieleichen haben meist kurze Blattstiele, aber lange Stiele an den Eichelständen. Beide Merkmale gemeinsam betrachten."),
  plant("haengebirke", "Hängebirke", "Betula pendula", "Laubbaum", ["Dreieckige bis rautenförmige, zugespitzte Blätter", "Doppelt gesägter Blattrand", "Junge Zweige meist kahl und mit kleinen Harzwarzen"], { fruehling: "Blüte meist April bis Mai; junge Zweige und Blätter vergleichen.", sommer: "Blattform und Zweigbehaarung gemeinsam prüfen.", herbst: "Blätter färben sich vor dem Laubfall; die Farbe allein trennt keine Birkenarten.", winter: "Weiße Rinde ist auffällig, aber nicht allein artsicher. Zweige und Standort ergänzen den Befund." }, "Moorbirke besitzt stärker behaarte junge Zweige. Birkenhybriden und variable Blattformen sind möglich.", "Lichtreiche Wald- und Pionierstandorte; nicht jede Birke an einem nassen Ort ist automatisch eine Moorbirke.", "Was hilft, Hängebirke und Moorbirke genauer zu vergleichen?", ["Nur die weiße Rindenfarbe", "Nur die Größe des Baums", "Blattform und Behaarung junger Zweige zusammen"], 2, "Auch andere Birken besitzen helle Rinde. Junge Zweige und Blätter liefern zusätzliche Merkmale; eine einzelne Farbe genügt nicht."),
  plant("bergahorn", "Bergahorn", "Acer pseudoplatanus", "Laubbaum", ["Meist fünflappige Blätter mit unregelmäßig gezähnten Rändern", "Blattunterseite graugrün", "Zweiflügelige Früchte; Blütenstände hängen"], { fruehling: "Blüte meist April bis Mai; die hängenden Blütenstände erscheinen nicht vor dem Laub.", sommer: "Lappen, Zähnung und Blattunterseite vergleichen.", herbst: "Geflügelte Doppelfrüchte ergänzen die Blattmerkmale; der Flügelwinkel ist variabel.", winter: "Gegenständige Zweige und Knospen können helfen. Eine einzelne Flügelfrucht ist kein vollständiger Bestimmungsnachweis." }, "Spitzahorn hat andere Blattspitzen und Blütenstände. Nicht jede handförmige Blattspreite ist ein Bergahorn.", "Wälder und Berghänge, auch häufig angepflanzt.", "Welche Kombination passt zum Bergahorn?", ["Fünflappige, gezähnte Blätter und hängende Blütenstände", "Immergrüne Nadelpaare und kurze Zapfen", "Runde ungeteilte Blätter und blau bereifte Steinfrüchte"], 0, "Bergahorn besitzt gelappte Laubblätter und zweiflügelige Früchte. Nadelpaare oder Schlehenfrüchte passen nicht zu dieser Art."),
  plant("hasel", "Hasel", "Corylus avellana", "Strauch", ["Breite, rundliche bis herzförmige Blätter", "Doppelt gezähnter Blattrand", "Nüsse mit einer unregelmäßig zerschlitzten Hülle"], { fruehling: "Männliche Kätzchen blühen meist Februar bis April vor dem Laubaustrieb. Weibliche Blüten zeigen kleine rote Narben.", sommer: "Breite Blätter und Blattrand betrachten; unreife Früchte können zusätzliche Hinweise geben.", herbst: "Nuss und Fruchthülle gemeinsam untersuchen, ohne allein daraus eine Verzehrfreigabe abzuleiten.", winter: "Kätzchen und Zweige bleiben als Vergleichsmerkmale. Die genaue Blütezeit schwankt mit Wetter und Standort." }, "Andere Haselarten und Zierformen kommen in Pflanzungen vor. Eine rundliche Blattspreite allein reicht nicht.", "Gebüsche, Hecken und Waldränder.", "Was erscheint bei der Hasel typischerweise vor dem Laubaustrieb?", ["Reife Eicheln", "Blühende männliche Kätzchen", "Aufrechte Tannenzapfen"], 1, "Haselkätzchen können schon früh im Jahr blühen. Haselnüsse entwickeln sich später; Eicheln und Tannenzapfen gehören zu anderen Pflanzen."),
  plant("eberesche", "Eberesche / Vogelbeere", "Sorbus aucuparia", "Laubbaum", ["Unpaarig gefiederte Blätter", "Viele gezähnte Teilblätter mit einem Endblättchen", "Helle Blütenstände und rote, kleine Apfelfrüchte"], { fruehling: "Blüte meist Mai bis Juni; gefiederte Blätter sind bereits vorhanden.", sommer: "Teilblätter zählen und ihren gesägten Rand ansehen.", herbst: "Rote Fruchtstände ergänzen die gefiederten Blätter. Rote Früchte allein bestimmen keine Art.", winter: "Blattnarben, Zweige und Knospen hinzunehmen. Das Fehlen von Früchten ist kein Gegenbeweis." }, "Esche hat ebenfalls gefiederte Blätter, aber andere Früchte. Rote Früchte kommen außerdem an vielen anderen Gehölzen vor.", "Wälder und Waldränder, auch im Bergland; örtliche Formen berücksichtigen.", "Wie ist ein typisches Ebereschenblatt aufgebaut?", ["Eine ungeteilte runde Blattspreite", "Fünf tief gelappte Abschnitte ohne Teilblättchen", "Unpaarig gefiedert mit einem Endblättchen"], 2, "Ein Ebereschenblatt besteht aus mehreren Teilblättern und einem Endblättchen. Ein gelapptes Ahornblatt ist dagegen eine zusammenhängende Spreite."),
  plant("schlehe", "Schlehe / Schwarzdorn", "Prunus spinosa", "Strauch", ["Dornige Zweige und dunkle Rinde", "Kleine, gezähnte Blätter", "Weiße Blüten vor dem Laub; später blaue bereifte Steinfrüchte"], { fruehling: "Weiße Einzelblüten erscheinen meist im April vor dem Laubaustrieb.", sommer: "Blätter und dornige Zweige gemeinsam ansehen.", herbst: "Die blau bereiften Steinfrüchte sind ein Zusatzmerkmal; keine Pflanze anhand einer Fruchtfarbe zum Verzehr bestimmen.", winter: "Dornige Kurztriebe und dunkle Zweige sind sichtbar. Mit anderen dornigen Gehölzen vergleichen." }, "Weißdorn blüht gewöhnlich später und besitzt gelappte Blätter. Dornen allein unterscheiden die beiden nicht.", "Hecken und Waldränder, von Tieflagen bis ins Bergland.", "Welche jahreszeitliche Beobachtung passt zur Schlehe?", ["Weiße Blüten vor dem Laubaustrieb", "Blüten erst lange nach dem Laubfall im Winter", "Immergrüne flache Nadeln"], 0, "Schlehenblüten erscheinen typischerweise vor ihren Blättern. Weißdorn besitzt im Frühjahr dagegen meist schon Laub, wenn er blüht."),
  plant("weissdorn", "Eingriffeliger Weißdorn", "Crataegus monogyna", "Strauch", ["Dornige Zweige", "Tief gelappte Laubblätter", "Weiße Blüten mit einem Griffel; rote Früchte meist mit einem Steinkern"], { fruehling: "Blüte meist Mai bis Juni, gewöhnlich mit vorhandenen Blättern.", sommer: "Tiefe Blattlappen und Dornen zusammen vergleichen.", herbst: "Rote Früchte ergänzen die Bestimmung. Griffel- und Steinkernzahl helfen bei ähnlichen Weißdornarten.", winter: "Zweige, Dornen und verbleibende Früchte können Hinweise geben, ersetzen aber keinen vollständigen Schlüssel." }, "Zweigriffeliger Weißdorn und Hybriden können ähnlich sein. Die Fruchtfarbe oder ein einzelnes Blatt genügt nicht für jede Artabgrenzung.", "Gebüsche und Hecken, häufig in wärmeren und trockeneren Lagen.", "Welches Merkmal ergänzt die Bestimmung des Eingriffeligen Weißdorns?", ["Zwei Nadeln in einem Bündel", "Ein Griffel und meist ein Steinkern je Frucht", "Blaue bereifte Steinfrüchte an unbelaubten Blütenzweigen"], 1, "Der Eingriffelige Weißdorn besitzt einen Griffel und gewöhnlich einen Steinkern. Bei Hybriden und ähnlichen Arten mehrere Merkmale prüfen."),
  plant("schwarzerle", "Schwarzerle", "Alnus glutinosa", "Laubbaum", ["Rundliche bis ovale Blätter", "Blattspitze oft stumpf oder eingebuchtet", "Kleine verholzte Fruchtstände, die Zäpfchen ähneln"], { fruehling: "Blüte meist Februar bis April. Junge Blätter können klebrig sein.", sommer: "Blattspitze und Umriss vergleichen; Blätter sind nicht immer gleich stark eingebuchtet.", herbst: "Verholzte Fruchtstände ergänzen die Blattmerkmale.", winter: "Alte Zäpfchen bleiben oft sichtbar. Sie sind keine Nadelbaumzapfen, sondern Fruchtstände eines Laubbaums." }, "Grauerle hat andere Blattmerkmale. Ein nasser Standort oder ein Zäpfchen allein ist keine sichere Artbestimmung.", "Ufer und feuchte Wälder.", "Wie sind die kleinen verholzten ‚Zäpfchen‘ der Schwarzerle einzuordnen?", ["Als abgebrochene Fichtenzapfen", "Als Beweis, dass die Erle ein Nadelbaum ist", "Als Fruchtstände eines Laubbaums"], 2, "Erlen sind Laubbäume. Ihre verholzten weiblichen Fruchtstände erinnern an kleine Zapfen, machen sie aber nicht zu Nadelbäumen."),
  plant("fichte", "Fichte", "Picea abies", "Nadelbaum", ["Einzeln sitzende, vierkantige Nadeln", "Nadeln stehen rings um den Zweig", "Reife Zapfen hängen und fallen als Ganzes ab"], { fruehling: "Junge Triebe und Nadeln ansehen; Blüte meist im Mai.", sommer: "Eine Nadel im Querschnitt vergleichen: vierkantig statt flach.", herbst: "Hängende reife Zapfen unterstützen die Bestimmung.", winter: "Nadeln bleiben erhalten. Zapfenstellung und Nadelbau lassen sich auch ohne Laubwechsel vergleichen." }, "Weißtanne besitzt flache Nadeln mit hellen Bändern unten und aufrechte Zapfen. Aus der Ferne die Kronenform nicht allein verwenden.", "Natürlich vor allem kühlere Waldlagen; vielerorts außerhalb ursprünglicher Vorkommen angepflanzt.", "Welche Zapfeneigenschaft passt zur Fichte?", ["Reife Zapfen hängen und fallen im Ganzen ab", "Zapfen stehen aufrecht und zerfallen am Baum", "Alle Früchte sind dreikantige Nüsse"], 0, "Fichtenzapfen hängen und können als ganze Zapfen am Boden liegen. Tannenzapfen stehen aufrecht und zerfallen bei Reife am Baum."),
  plant("weisstanne", "Weißtanne", "Abies alba", "Nadelbaum", ["Flache Nadeln, Unterseite mit zwei hellen Bändern", "Nadeln an vielen Zweigen zweizeilig angeordnet", "Aufrechte Zapfen zerfallen bei Reife am Baum"], { fruehling: "Junge Zweige und Nadeln vergleichen; Blüte meist im Mai.", sommer: "Auch die Nadelunterseite ansehen, nicht nur die Oberseite.", herbst: "Reife Zapfen zerfallen am Baum; die Spindel kann stehen bleiben.", winter: "Die Nadeln bleiben erhalten. Ganze ‚Tannenzapfen‘ am Boden stammen oft von anderen Nadelbäumen." }, "Fichte hat vierkantige Nadeln und hängende Zapfen. Nadelanordnung kann mit der Lage des Zweigs variieren.", "Wälder mit geeigneten, tiefgründigen Böden, besonders in montanen Lagen.", "Was unterscheidet reife Weißtannenzapfen von Fichtenzapfen?", ["Sie liegen immer vollständig am Boden", "Sie stehen aufrecht und zerfallen am Baum", "Sie besitzen keine Samen"], 1, "Weißtannenzapfen stehen aufrecht; ihre Schuppen und Samen lösen sich, während die Spindel zurückbleiben kann. Fichtenzapfen fallen als Ganzes."),
  plant("waldkiefer", "Waldkiefer / Waldföhre", "Pinus sylvestris", "Nadelbaum", ["Nadeln paarweise in einem Bündel", "Nadeln auf der Innenseite bläulich grün", "Rinde wenigstens im oberen Kronenbereich oft rostrot"], { fruehling: "Nadelbündel und junge Triebe betrachten; Blüte meist im Mai.", sommer: "Nadelzahl je Bündel zusammen mit Rinde und Zapfen prüfen.", herbst: "Reife kurze Zapfen ergänzen die Bestimmung; nicht jede zweinadelige Kiefer ist eine Waldkiefer.", winter: "Die Nadeln bleiben erhalten. Rindenfarbe im Kronenbereich ist ein zusätzlicher Hinweis." }, "Andere Kiefern besitzen ebenfalls zwei Nadeln je Bündel. Nadelzahl allein reicht deshalb nicht bis zur Art.", "Lichtreiche Wälder und nährstoffarme Pionierstandorte; auch angepflanzt.", "Welche Aussage zur Kiefernbestimmung ist richtig?", ["Zwei Nadeln je Bündel beweisen immer Waldkiefer", "Rote Rinde reicht für jede Baumartbestimmung", "Nadelbündel, Rinde und Zapfen gemeinsam vergleichen"], 2, "Auch andere Kiefern sind zweinadelig. Mehrere Merkmale zusammen liefern eine belastbarere Einordnung als ein einzelnes Merkmal."),
];

export const plantAtlasQuestions = plantAtlasEntries.map(entry => ({ ...entry.quiz, plantId: entry.id }));
export function filterPlants(query = "", group = "alle") {
  const text = String(query).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replaceAll("ß", "ss").trim();
  return plantAtlasEntries.filter(entry => (group === "alle" || entry.group === group) && `${entry.name} ${entry.latin} ${entry.features.join(" ")} ${entry.habitat}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replaceAll("ß", "ss").includes(text));
}
