export const practiceCatalog = [
  ["ansitz", "Ansitz-Simulator", "target"],
  ["drueckjagd", "Drückjagd-Wissen üben", "practice"],
  ["pirsch", "Pirsch-Wissen üben", "practice"],
  ["keiler", "Keiler-Erkennung", "deer"],
  ["schusszeichen", "Schusszeichen-Trainer", "alert"],
  ["trefferzonen", "Trefferzonen-Trainer", "target"],
  ["wild", "Wildkunde", "deer"],
  ["wildansprache", "Wildansprache-Trainer", "deer"],
  ["nachsuche", "Nachsuche-Simulator", "paw"],
  ["schussfeld", "Schussfeld-Beurteilung", "target"],
  ["revier", "Revierkunde & Geländeformen", "tree"],
  ["trophaeen", "Trophäenbewertung", "deer"],
  ["nachtjagd", "Nachtjagd-Wissen üben", "moon"],
  ["waermebild", "Wärmebild-Ansprechen", "eye"],
  ["entfernung", "Entfernungsschätzung", "ruler"],
  ["beschuss", "Kugelfang & Sicherheitstrainer", "shield"],
  ["krankeswild", "Krankes Wild erkennen", "health"],
  ["familienverbaende", "Wildfamilien & Sozialstrukturen", "deer"],
  ["verhalten", "Wildverhalten beurteilen", "eye"],
  ["lauscher", "Lauscher- und Zeichendeutung", "deer"],
  ["wind", "Wind & Pirschrichtung", "wind"],
  ["mond", "Mondphasen-Revieraktivität", "moon"],
  ["ansprache_rehwild", "Rehwild-Ansprechen", "deer"],
  ["ansprache_schwarzwild", "Schwarzwild-Ansprechen", "deer"],
  ["ansprache_rotwild", "Rotwild-Ansprechen", "deer"],
  ["wildspuren", "Fährten- & Spurenkunde", "practice"],
  ["kugelwirkung", "Geschosswirkung-Demo", "target"],
  ["wildalarm", "Wild reagiert – was nun?", "alert"],
  ["optik", "Optik richtig nutzen", "binoculars"],
  ["waffenhandhabung", "Waffenhandhabungs-Simulator", "shield"],
]

// Exercises can belong to several learning areas; their URL and menu order stay stable.
export const practiceCategories = {
  ansitz: ["jagdpraxis", "wildkunde", "waffen-sicherheit"],
  drueckjagd: ["jagdpraxis", "waffen-sicherheit", "hundewesen"],
  pirsch: ["jagdpraxis", "natur-revier"],
  keiler: ["jagdpraxis", "wildkunde"],
  schusszeichen: ["jagdpraxis", "wildkunde", "waffen-sicherheit", "tierschutz-verantwortung"],
  trefferzonen: ["jagdpraxis", "wildkunde", "waffen-sicherheit"],
  wild: ["jagdpraxis", "wildkunde"],
  wildansprache: ["jagdpraxis", "wildkunde"],
  nachsuche: ["jagdpraxis", "hundewesen", "tierschutz-verantwortung"],
  schussfeld: ["jagdpraxis", "waffen-sicherheit", "natur-revier"],
  revier: ["jagdpraxis", "natur-revier", "wald-pflanzen"],
  trophaeen: ["jagdpraxis", "wildkunde"],
  nachtjagd: ["jagdpraxis", "waffen-sicherheit", "ausruestung-technik"],
  waermebild: ["jagdpraxis", "wildkunde", "ausruestung-technik"],
  entfernung: ["jagdpraxis", "waffen-sicherheit", "ausruestung-technik"],
  beschuss: ["jagdpraxis", "waffen-sicherheit"],
  krankeswild: ["jagdpraxis", "wildkunde", "wildbret-gesundheit"],
  familienverbaende: ["jagdpraxis", "wildkunde"],
  verhalten: ["jagdpraxis", "wildkunde", "tierschutz-verantwortung"],
  lauscher: ["jagdpraxis", "wildkunde"],
  wind: ["jagdpraxis", "natur-revier"],
  mond: ["jagdpraxis", "natur-revier"],
  ansprache_rehwild: ["jagdpraxis", "wildkunde"],
  ansprache_schwarzwild: ["jagdpraxis", "wildkunde"],
  ansprache_rotwild: ["jagdpraxis", "wildkunde"],
  wildspuren: ["jagdpraxis", "wildkunde", "natur-revier"],
  kugelwirkung: ["jagdpraxis", "waffen-sicherheit"],
  wildalarm: ["jagdpraxis", "wildkunde", "tierschutz-verantwortung"],
  optik: ["jagdpraxis", "ausruestung-technik"],
  waffenhandhabung: ["jagdpraxis", "waffen-sicherheit"],
};
