export const practiceCatalog = [
  ["ansitz", "Ansitz-Simulator", "target"],
  ["drueckjagd", "Drückjagd-Wissen üben", "practice"],
  ["pirsch", "Pirsch-Wissen üben", "practice"],
  ["keiler", "Keiler-Erkennung", "deer"],
  ["schusszeichen", "Schusszeichen-Trainer", "alert"],
  ["trefferzonen", "Trefferzonen-Trainer", "target"],
  ["wild", "Wildkunde", "deer"],
  ["wildansprache", "Wildansprache-Trainer", "deer"],
  ["nachsuche", "Nachsuche-Simulator", "paw"],
  ["schussfeld", "Schussfeld-Beurteilung", "target"],
  ["revier", "Revierkunde & Geländeformen", "tree"],
  ["trophaeen", "Trophäenbewertung", "deer"],
  ["nachtjagd", "Nachtjagd-Wissen üben", "moon"],
  ["waermebild", "Wärmebild-Ansprechen", "eye"],
  ["entfernung", "Entfernungsschätzung", "ruler"],
  ["beschuss", "Kugelfang & Sicherheitstrainer", "shield"],
  ["krankeswild", "Krankes Wild erkennen", "health"],
  ["familienverbaende", "Wildfamilien & Sozialstrukturen", "deer"],
  ["verhalten", "Wildverhalten beurteilen", "eye"],
  ["lauscher", "Lauscher- und Zeichendeutung", "deer"],
  ["wind", "Wind & Pirschrichtung", "wind"],
  ["mond", "Mondphasen-Revieraktivität", "moon"],
  ["ansprache_rehwild", "Rehwild-Ansprechen", "deer"],
  ["ansprache_schwarzwild", "Schwarzwild-Ansprechen", "deer"],
  ["ansprache_rotwild", "Rotwild-Ansprechen", "deer"],
  ["wildspuren", "Fährten- & Spurenkunde", "practice"],
  ["kugelwirkung", "Geschosswirkung-Demo", "target"],
  ["wildalarm", "Wild reagiert – was nun?", "alert"],
  ["optik", "Optik richtig nutzen", "binoculars"],
  ["waffenhandhabung", "Waffenhandhabungs-Simulator", "shield"],
]
