import Link from "next/link";
import LearningToolLayout from "../components/LearningToolLayout";
import styles from "../styles/LearningExperience.module.css";

export default function Hilfe() {
  return <LearningToolLayout title="Hilfe zu Jagdlatein" description="Anmeldung, Lernzugang und Abonnements einfach erklärt." icon="community" eyebrow="Kontakt und Hilfe" hideCommunity>
    <section className={styles.panel}><h2>Wir helfen dir weiter</h2><p>Schreibe an <a href="mailto:info@jagdlatein.de">info@jagdlatein.de</a>. Beschreibe, was du öffnen möchtest und welche Meldung erscheint. Nenne bei der iOS-App möglichst auch die App-Version. Bitte sende keine Passwörter, Anmeldecodes oder Zahlungsdaten.</p></section>
    <section className={styles.panel}><h2>Anmelden und registrieren</h2><p>Für dein erstes Jagdlatein-Konto wählst du „Kostenlos registrieren“ und bestätigst deine E-Mail-Adresse. Für ein vorhandenes Konto verwendest du „Anmelden“. Registrierung und Anmeldung schließen kein kostenpflichtiges Abo ab.</p><p>Ein Anmeldecode gilt zehn Minuten. Prüfe auch den Spamordner. Wenn du einen neuen Code anforderst, verwende den neuesten. Meldet die App einen Versandfehler, versuche es später erneut oder kontaktiere uns.</p><p>Eine Anmeldung im Safari-Browser meldet dich nicht automatisch in der iOS-App an. Nutze in der App dieselbe E-Mail-Adresse wie für dein Jagdlatein-Konto.</p><div className={styles.actions}><Link className={styles.secondary} href="/login">Zur Anmeldung</Link><Link className={styles.secondary} href="/registrieren">Konto erstellen</Link></div></section>
    <section className={styles.panel}><h2>Apple-Abo und Lernzugang</h2><p>Auf iPhone und iPad öffnest du in der nativen App „Abo und Käufe“. Melde dich zuerst mit deinem Jagdlatein-Konto an. Apple zeigt den verfügbaren Monatspreis und ein gegebenenfalls für dich verfügbares Einführungsangebot vor deiner Bestätigung. Das Abo verlängert sich automatisch, bis du es bei Apple kündigst.</p><p>Ein bereits berechtigtes Jagdlatein-Konto kannst du auch in der iOS-App verwenden. Für diesen Zugang ist kein zweites Abo erforderlich.</p></section>
    <section className={styles.panel}><h2>Käufe wiederherstellen</h2><p>Öffne „Abo und Käufe“ und wähle „Käufe wiederherstellen“. Du brauchst das Jagdlatein-Konto, dem der Kauf ursprünglich zugeordnet wurde, und den passenden Apple-Account. Die Wiederherstellung löst keinen neuen Kauf aus.</p><p>Ist der Button gesperrt, prüfe zuerst deine Jagdlatein-Anmeldung. Bei einer vorübergehend fehlenden Verbindung lade die Übersicht erneut. Ein abgelaufenes oder erstattetes Abo erhält durch die Wiederherstellung keinen neuen Zugangszeitraum.</p></section>
    <section className={styles.panel}><h2>Abo verwalten oder kündigen</h2><p>Ein Apple-Abo verwaltest du über „Apple-Abos verwalten“ in der App oder in den Apple-Einstellungen unter deinem Account und „Abonnements“. Nach einer Kündigung bleibt ein noch gültiger Zugangszeitraum bis zu seinem bestätigten Ende nutzbar.</p><p>Ein auf der Website abgeschlossenes PayPal-Abo verwaltest du unter „Mein Konto“ beziehungsweise bei PayPal. Die Abrechnung bleibt beim Anbieter, bei dem du das Abo abgeschlossen hast.</p><Link className={styles.secondary} href="/konto">Mein Konto öffnen</Link></section>
    <section className={styles.panel}><h2>Konto und persönliche Daten löschen</h2><p>Die direkte Kontolöschung findest du nach ihrer Freischaltung unter „Mein Konto“. Dort bestätigst du deine Anmeldung erneut und die angezeigten Löschhinweise. Du kannst uns auch unter <a href="mailto:info@jagdlatein.de?subject=Kontol%C3%B6schung">info@jagdlatein.de</a> kontaktieren.</p><p>Die Kontolöschung kündigt ein laufendes Apple- oder PayPal-Abo nicht automatisch. Verwalte und kündige es zuvor beim jeweiligen Anbieter. Lokal gespeicherte Daten auf anderen Geräten werden durch die Serverlöschung nicht automatisch entfernt.</p><Link className={styles.secondary} href="/datenschutz">Datenschutzhinweise</Link></section>
    <section className={styles.panel}><h2>Community und fachliche Fragen</h2><p>Neue Themen und Antworten reichen Lernende zunächst zur Prüfung ein. Bis zur Freigabe sehen nur du und die Moderation deinen Beitrag. Unter „Meine Einreichungen“ findest du deine noch offenen oder nicht freigegebenen Beiträge. Bei der Prüfung wird auch dein öffentlich angezeigter Lernname berücksichtigt.</p><p>Eine Freigabe bestätigt die Einhaltung der Community-Regeln und ist kein fachliches Prüfsiegel. Prüfe Aussagen anhand verlässlicher Quellen. Bei einem problematischen Beitrag nutze zusätzlich „Beitrag melden“. Über „Nutzer blockieren“ bei einem fremden Beitrag blendest du den Austausch zwischen euch aus. Unter „Blockierte Nutzer“ kannst du die Blockierung aufheben. Du kannst uns auch direkt per E-Mail kontaktieren.</p><p>Fragen zu Lerninhalten helfen uns, Jagdlatein zu verbessern. Nenne den Kurs, das Thema und die betreffende Aussage. Community-Beiträge stammen von Lernenden.</p></section>
  </LearningToolLayout>;
}
